openapi: 3.0.0
info:
  title: Tiny API
  version: 1.0.0

paths:
  /ping:
    get:
      responses:
        '200':
          description: Pong response
          content:
            text/plain:
              schema:
                type: string
                example: pong
